micronaut:
  application:
    name: demo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/service-crud?ssl=false
    username: root
    password: root
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'com.example.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
#jpa:
#  default:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        show_sql: true